const DEFAULTS = {
  siteTitle: 'Jefferson Rocha Livros',
  tagline: 'Coleção premium',
  heroTitle: 'Descubra histórias que transformam a sua rotina.',
  heroText: 'Uma experiência elegante de leitura com lançamentos, promoções e títulos especiais em um só lugar.',
  whatsapp: '5511999999999',
  instagram: 'https://instagram.com/brian_lewis_2',
  footerText: '© 2026 Jefferson Rocha Livros. Todos os direitos reservados.',
  creditText: 'Desenvolvido por Brian Lewis',
  categories: [
    'Ação e Aventura',
    'Arte',
    'Autoajuda',
    'Biografia',
    'Ciência',
    'Clássicos',
    'Contos',
    'Crime',
    'Direito',
    'Economia',
    'Educação',
    'Espiritualidade',
    'Fantasia',
    'Ficção Científica',
    'Ficção Histórica',
    'Filosofia',
    'Finanças',
    'Gastronomia',
    'História',
    'Humor',
    'Infantil',
    'Informática e Tecnologia',
    'Jovem Adulto',
    'Literatura Brasileira',
    'Literatura Estrangeira',
    'Marketing',
    'Matemática',
    'Medicina',
    'Mistério',
    'Música',
    'Negócios',
    'Poesia',
    'Política',
    'Psicologia',
    'Religião',
    'Romance',
    'Saúde e Bem-estar',
    'Suspense',
    'Terror',
    'Thriller',
    'Turismo',
    'Viagem'
  ]
};

module.exports = { DEFAULTS };
